import "../../public/css/globals.css";
import "../../public/fonts/font.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer"; 

export const metadata = {
  title: "EAS",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '../public/img/logo.png', 
        href: '../public/img/logo.png', 
      }
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head> 
        <link rel="icon" type="image/png" href="../public/img/logo.png" /> 
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}